德育教育是素质教育的基石
【摘要】对素质教育的本质进行简要分析，阐述了加强德育教育的前提，分析了德育教育的重要举措，对德育教育的途径和目的进行剖析，指出德育教育是素质教育的基石。

* 一、加强德育渗透，培养正确的世界观、人生观和价值观
实施素质教育首先是思想观念的转变，而思想观念转变的一个重要途径就是在实施素质教育过程中进行德育渗透，充分利用素质教育的主阵地――课堂，对实施素质教育的主体――学生，进行思想渗透和灌输。如何加强学校各学科的德育渗透，是当前教改中一个亟待解决的重要课题。在全社会普遍重视加强和改进未成年人思想道德建设的大氛围下，学校作为专职教育单位，“把德育放在学校一切工作的首位”已是我们的共识。加强对学生进行政治教育、思想教育、道德教育、法纪教育和心理品质教育，对促进学生全面发展起着主导的决定性功能。
作为小学，尤其是低年级的孩子，正是开始对人生对世界对生活有理性认知的时候，要对学生进行“五爱”教育，引导学生形成正确的世界观、人生观和价值观，就显得相当重要。思想政治素质是最重要的素质，是素质教育的灵魂。学生成长的过程，不仅仅是增长知识、发展智力、增强体质的过程，更是其人格形成和发展的过程。随着当今世界信息科学技术和物质生产的迅猛发展，社会对人的素质规格提出了更高的要求，学校只有把德育教育作为全面育人的首要任务，才能使学校的素质教育取得显著成绩。
* 二、加强德育教育的前提是提高教师的品德素质
** 2.1教师要树立正确的教育观点
教育是培养人的活动，而培养人不能只限于对少数尖子生的培养。某些教师对那些学习好、听话、反应快的学生格外器重，愿意和他们亲近，而对那些不够顺从，反应较慢，学习成绩较差的学生则不愿多交往，多接触。有些教师甚至对一些所谓的差生表现出厌弃或鄙视的态度。其实，那些学生更需要教师的关怀和体贴，需要教师与他们多接触、多交往、多沟通，以消除他们与教师之间的隔阂和抵触，与他们建立起一种没有歧视和压抑，没有嘲笑与斥责的，宽松和谐的师生关系，增强他们的自尊心和上进心，促使他们思想觉悟与行为的转变。
** 2.2以教师的人格去影响学生的心理
列宁说：“一个人早期在思想上所受到潜移默化的影响所形成的道德观念，对其成长影响极大。”所以教师更应以自己完美的人格魅力为学生作榜样，影响他们的成长。
令我们痛心的5.12大地震中，都江堰市聚源中学的的校舍倒塌了，240余名师生遇难。当地震发生时，老师首先想到的就是学生，迅速组织学生逃离教室，而他们却最后离开教室，不幸的是他们中很多没有逃离死难。有些老师的孩子也在这个学校上学，可是那一刻，他们无暇顾及自己的孩子，只是希望他们的学生可以平安。他们遇难了，可是他们的生命却放射出了璀璨的光芒。还有许许多多的学校的教师，他们面对生死垂危的那一刻，想到的是那些年轻的生命，把生的希望留给了学生。他们用生命诠释了教师的人格，用血肉托起了明天的太阳。
* 三、加强德育教育的重要举措是创设良好的校园环境
俗话说“近朱者赤，近墨者黑”，讲的是人的成长与发展受周围环境的制约与影响。好的环境能促进人的发展，差的环境能制约人的发展。历史上有“孟母三迁”之说，说明我国古人已经很重视教育的环境影响。
学校是教育人的场所，营建良好的校园环境，规范校园的文化建设，对于全面贯彻教育方针，促进和提高受教育者素质有着十分重要的意义。净化校园，干净、整洁、富有健康的情趣，可激发学生积极的学习热情，并促进学生养成良好的卫生习惯。绿化的校园，绿树成荫、绿草成片、百花争艳，可稳定学生情绪，消除疲劳，保护学生视力，促进学生身体素质的全面发展。美化的校园，朴素、雅致、鲜明、协调，能激起学生的审美和高雅情趣，促进学生审美素质的提高。
苏霍姆林斯基说过：“美是一种心灵的体操，它使我们精神正直、心地纯洁、情感和信念端正。”可见优美的环境对学生心理素质和思想品德素质的发展也起着重要作用。人们总是追求美，渴望美。人们在美的环境中，在体验、享受美的同时，情感得到熏陶、净化、升华，从而促进内因的变化。
* 四、加强德育教育的重要途径是以养成教育为基础
养成教育，就是培养学生良好行为习惯的教育。叶圣陶先生说：“教育是什么，往简单方面说，只须一句话，就是要养成良好的习惯。”
学生的良好思想品德的培养，要从大处着眼，小处着手，从养成教育开始，从一点一滴抓起。所以，培养学生良好的行为规范，是作为老师的基本任务。在每一次课堂教学中，作为教师，都要着手抓基础文明行为的养成，使养成教育工作系列化，把好课堂教学纪律等。教师的身传言教与学生自我教育相结合，培养良好的文明礼仪规范，提高文明素质。课内重视学习习惯的培养教育，小至上课的一个坐势，大至学习某类固定课型的学习方法，都应该要求贯穿于每一堂课的教学之中。上课时，如果有学生开小差，教师要有意识地、采取适当方法予以引导；有同学做小动作，教师要边讲课边下意识地走到该同学身边，直至学生专心听讲。学生听课过程当中，我们要注重培养学生专心听课的习惯。专心与否，是学生能否提高学习成绩的重要判断标准。只有通过一言一行的严格要求，才能使学生做到严以律己。养成良好的道德，首要是要有良好的日常养成，文明、礼貌、卫生等等细小的环节，都是德育教育的外在表现形式。加强养成教育，就是对学生德育教育的第一步。
* 五、加强德育教育的重要目标是培育四有公民
我国新时期的教育方针是建设有中国特色社会主义理论的一个重要组成部分，是指导我国各级各类教育的总方针，它的根本任务就是加强德育教育，全面提高教学质量，具有根本性的指导意义，对于我们教师来说，应着眼于德育教育，自觉按照未来社会对人才的知识结构，能力结构以及伦理道德规范的要求塑造青少年一代，为培养合格的社会主义现代化人才打下坚实的基础。小学生品德好，对于今后的深造和步入社会有重要的作用，德育教育对人们的一生具有重大而深远的影响，对人们素质的提高具有很大的促进作用，培养有理想、有道德、有文化、有纪律的社会主义公民，都有着重要意义。
“课课有德育，人人是德育工作者”深入人心，及时总结，充分交流，提升德育工作水平。使未成年人在学校能时时处处受到传统美德精神的熏陶，从课堂中得到科学文化知识和思想道德的“双丰收”，在未成年人思想道德建设中发挥了积极有效的功能。
