思维导图在小学数学中的合理应用

* 一、思维导图的概念
  思维导图(Mind Mapping)是一种将发散性思考(Radiant Thinking)具体化的方法。通俗地说，思维导图是一个简单、有效、美丽的思维工具，它依据全脑的概念，按照大脑自身的规律进行思考，全面调动左脑的逻辑、顺序、条例、文字、数字以及右脑的图像、想象、颜色、空间、整体思维，使大脑潜能得到最充分的开发，从而极大地发掘人的记忆、创造、身体、语言、精神、社交等各方面的潜能。
  思维导图基于对人脑的模拟，它的整个画面正像一个人大脑的结构图（分布着许多“沟”与“回”）；其次，这种模拟突出了思维内容的重心和层次；第三，这种模拟强化了联想功能，正像大脑细胞之间无限丰富的连接；第四，人脑对图像的加工记忆能力大约是文字的1000倍。思维导图能够让人们更有效地把信息存放在大脑，或是把信息从大脑中取出来。
  有相当多的研究资料表明：思维导图在英国、美国、澳大利亚、新加坡等国家的教育领域有广泛应用，在提高教学效果方面成效显著。同时思维导图的可创造性和可延伸性对学生的认知结构产生积极影响，使学生形成终身认知的科学知识结构是可能的。
  由此可知，形象思维是一种值得培养、并能运用在数学领域中的有效的思维方式。但思维导图作为一种评价工具、有效的学习工具和创造工具，在运用到小学数学教学和学习的过程中，有相当多需要注意的地方。本文将对些合理性进行研究，并试图探寻一些适合教学的方式。

* 二、形象思维在小学数学中的地位和作用
  抽象性与逻辑性是我们对数学的一般理解。但在《新课标》中对小学数学的学习内容和目标上的阐述，让我们对小学数学有了另一番理解。
  《小学数学新课标》中对小学数学的学习内容定义了以下几个方面并给定了其达成目标。在数与代数方面，《新课标》指出“应帮助学生建立数感和符号意识，发展运算能力，树立模型思想”；在图形与几何方面，《新课标》指出“应帮助学生建立空间观念”，“直观与推理是‘图形与几何’学习中的两个重要方面”；在统计与概率方面，《新课标》指出 “帮助学生逐渐建立起数据分析的观念是重要的”；在综合与实践方面，《新课标》指出“‘综合与实践’是以一类问题为载体，学生主动参与的学习活动，是帮助学生积累数学活动经验的重要途径”。
  “模型思想”属于形象思维中的经验形象；“空间观念”、“数据观念”属于形象思维中的直观形象；“综合实践”方面的培养的正是形象思维中的创新形象。
  由上可知，《新课标》在小学阶段的数学学习主要以培养学生的形象思维和开放性认知结构为主，这不仅符合小学生形象思维占优，思维活跃，跳跃性强的特点，更为学生的终身认知打下基础。
  然而我们在对形象思维的理解上存在一些误区，认为数学中的形象思维须依据几何图形的教学，从而把数学形象思维能力的培养也简单地局限在几何图形的教学之中，甚或对形象思维简单地等同与空间思维，这样的理解是不利于我们开展课堂教学，并可能对学生的终身认知也产生负面影响。由此我们对《课标》的解读上也存在了一定的偏失。由于认识上的一些偏失，在教学环节的设定上也存在一定的不符合形象思维培养特点的问题。如创设情境后，教师一般会问一句：“你能发现哪些数学问题吗？”学生会过多地从一些数学技巧性的方面去提出一些问题。学生的思维就此从情境中出脱离出来，回到平时所理解的“数学严谨抽象”的意义上来。
  形象思维的发展程度在一定程度上决定了其他思维的发展程度。国内外研究表明，形象思维先于其他思维的发展，形象思维的发展程度在一定程度上决定了其他思维的发展程度。
  爱因斯坦曾这样描述过他的思维过程：“我思考问题时，不是用语言进行思考，而是用活动的跳跃的形象进行思考，当这种思考完成以后，我要花很大力气把它们转换成语言。”另一位诺贝尔奖莸得者李政道从上世纪80年代起，每年回国两次倡导科学与艺术的结合。他在北京召开“科学与艺术研讨会”，请黄胄、华君武、吴冠中等著名画家“画科学”。李政道的画题都是近代物理最前沿的课题，涉及量子理论、宇宙起源、低温超导等领域。艺术家们用他们擅长的右脑形象思维的方式，以绘画的形式形象化的表现了这些深奥的物理学原理。
  从两位大家的言行中我们看到形象思维的在思维中的地位。而小学阶段学生形象思维占优的特点让我们想到此时是培养学生形象思维的最佳时机。

* 三、形象思维可以用合适的方式进行培养
  形象思维是凭借头脑中已储存的表象进行的思维。而“每一种进入大脑的资料，不论是感觉、记忆或是想法，包括文字、数字、符号、食物、香气、线条、颜色、意象、节奏、音符等，都可以成为表象，而这一表象就可以成为一个思考中心，并由此中心向外发散出成千上万的挂勾，每一个挂勾代表与中心主题的一个连结，而每一个连结又可以成为另一个中心主题，再向外发散出成千上万的挂勾……这些挂勾连结可以视为你的记忆，也就是你的个人数据库。”这一“数据库”的容量和组织形式决定了形象思维的优劣程度。思维导图正是基于对人脑的模拟，与这一“数据库”的储存方式和组织结构和思维导图的“构图”方式不谋而合。
  数学中的形象思维主要包含以下几个方面：直观形象，经验形象，创新形象，意会形象。而这几个方面又能和思维导图的几个主要特征对应，所以说利用思维导图的形象性和结构性来提升学生的数学形象思维是可行的。


* 四、合理利用思维导图进行教学重在思维
** 绘制思维导图的本末倒置
  在思维导图被各行各业都广泛应用的今天，有相当多的思维导图培训班。在教育行业，也有相当多的老师开始学习研究并在教学中实践思维导图。这些实践都在不同程度上为我们提供了相当多间接的经验。
  但是，就目前的现状而言，有相当多的参考文献讲述的是如何绘制漂亮美观的思维导图，甚至有许多人有这样的强迫性倾向，即他所做的每件事，阅读的每本书都要用思维导图去绘制。这种方法无疑于本末倒置。
  事实上，在传统的教学中，教师们也都在不同程序上利用了思维导图的功能，比如在每一单元教学结束后，教师通常会将本单元的重难点以花括号或框图的形式总结出来，这就是思维导图的一种应用方式。现在所提倡的思维导图更多是要制作颜色不一，美观大方的图，这种制作往往会花费太多的功夫，结果就使得人们的思维被绘图所中断，失却了思维导图的原有意义。

** 针对低年纪小学生的思维培训方式
  根据国外某知名网站的的调查报告，思维导图软件用得最多的领域前10名是：待办事宜、准备演示、做笔记、问题解决、项目计划、做决定、知识管理、项目管理、个人思考和写作；对于小学生而言，导图本身的颜色和形状会使孩子们产生兴趣，但导图表达的逻辑却并不是小学生所能理解和具备的。单纯将思维导图用于学生对课本知识的学习，无疑会增加学生的学习负担，同时会起到事倍功半的效果。
  对于小学三年以下的学生而言，思维导图应该多用于思维训练，比如对生活某种东西的认知，引发相似的联想，进一步无限地扩大想象。心理学研究表明，人的思维具备放射性和跳跃性，而于对孩子们而言，这两种性质表现更为突出。以思维导图对孩子们进行生活认识的训练会较好地强化孩子思维的拓展性，在我所任教的班级，每次练习课都会拿出十分钟的时间，将提前准备好的和课程相关的生活概念向学生展示，同时要求孩子们尽可能地以我所展示的概念进行发散性地思维，尽管每名学生的结果都不同，但全都对这项活动表现出了极大的兴趣，而在课后，我会适时地选择时间对学生们的练习进行点评，同时将数学的概念向他们展示，这种教学方法使学生们对于课本的理解不再停留在死记硬背的阶段，而是融入在日常生活中，知识从死的变成活的了。而阶段性的测试成绩表明，采用这种方式进行的教学，使学生成绩稳步提升，更重要的是学生人逐渐对这门课程表现出了极大的热情。

* 五、传统教育与思维导图的有机结合
  传统教育强调的是知识的传授；思维导图强调的是从已有的知识发掘其联系，从而产生未知的知识。两者对于教学而言都是重要的有机组成部分。传统教育的不足之处是单调枯燥，而饱受教育界学者诟病的更是应试教育了。但就目前的教育制度而言，应该教育是相对公平的一种竞争方式。对于教师而言，只有在加强学生应试教育本领的同时，也要不断提高其素质能力的培养，对于后者，更要从思维角度为其拓展而不固化，要为学生打好良好的思维基础。在这方面，思维导图就扮演了较好的作用，采用灵活的方式，将思维导图本身的理念和方法教给学生，让他们不仅仅是照着书本上的提纲去学习去复习，更要让他们自己用自己的思维去总结去发现课本中知识的联系，在发现和总结的过程中，他们不但会对课本有更深层次的理解，更重要的是会逐渐产生浓厚的兴趣，从而达到提高教学成绩的目的。
